version: '3.8'

services:
  # Servicio de la aplicación Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamingpro_dashboard
    restart: always
    ports:
      - "1020:3000" # Mapear puerto 1020 del host al 3000 del contenedor
    environment:
      - DATABASE_URL=${DATABASE_URL} # Usar la variable de entorno para la conexión a la BD externa
      - NEXTAUTH_URL=http://localhost:1020
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - streamingpro_network

networks:
  streamingpro_network:
    driver: bridge
